# EDA

In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

### Pined the target directory

In [49]:
current_path = Path().cwd()
target_dir = current_path.parent.joinpath("data","raw")
print(target_dir)

/home/jojo/Documentos/ML_IA/Pruebas_Tecnicas /constructora-costos/data/raw

Read the csv's

In [50]:
historical_equipment = pd.read_csv(target_dir / 'historico_equipos.csv', parse_dates=['Date'])
historical_x = pd.read_csv(target_dir / 'X.csv', parse_dates=['Date'])
historical_y = pd.read_csv(target_dir / 'Y.csv', sep=';', decimal=',', parse_dates=['Date'])
historical_z = pd.read_csv(target_dir / 'Z.csv', parse_dates=['Date'])

In [51]:
print(f"train:{historical_equipment.shape}")
print(f"test:{historical_x.shape}")
print(f"test:{historical_y.shape}")
print(f"test:{historical_z.shape}")

train:(3530, 6)
test:(9144, 2)
test:(4485, 2)
test:(3565, 2)

Created a fuction to view the data, nulls, max and min date

In [52]:
def inspect_df(df:pd.DataFrame, name:str) -> None:
  """
  Function 
  """
  print(f"{name}")
  print(f"shape:{df.shape}")
  print(f"Period: {df.select_dtypes('datetime64').min().values} "
        f"→ {df.select_dtypes('datetime64').max().values}"
        if not df.select_dtypes('datetime64').empty else "")
  print("Columns and types:")
  print(df.dtypes)
  print("\nNulls:")
  nulls = df.isnull().sum()
  print(nulls[nulls > 0] if nulls.any() else "  Sin nulos")
  print("\nFirst rows:")
  display(df.head(3))
  print("\nLast rows:")
  display(df.tail(3))
  print(f"{'='*40}")

After run the function, appers a problem with the date, so its transform the date to the correct format and type

In [53]:
historical_y['Date'] = pd.to_datetime(historical_y['Date'], format='%d/%m/%Y')

In [54]:
inspect_df(historical_equipment,'historico_equipos.csv')
inspect_df(historical_x,'X.csv')
inspect_df(historical_y,'Y.csv')
inspect_df(historical_z,'Z.csv')

historico_equipos.csv
shape:(3530, 6)
Period: ['2010-01-04T00:00:00.000000'] → ['2023-08-31T00:00:00.000000']
Columns and types:
Date             datetime64[us]
Price_X                 float64
Price_Y                 float64
Price_Z                 float64
Price_Equipo1           float64
Price_Equipo2           float64
dtype: object

Nulls:
  Sin nulos

First rows:

        Date  Price_X  Price_Y  Price_Z  Price_Equipo1  Price_Equipo2
0 2010-01-04    80.12    527.5  2225.25         434.73         931.73
1 2010-01-05    80.59    527.5  2246.50         449.97         968.56
2 2010-01-06    81.89    527.5  2302.50         444.48         960.51

Last rows:

           Date  Price_X  Price_Y  Price_Z  Price_Equipo1  Price_Equipo2
3527 2023-08-29    85.49   545.33  2116.25         460.42         901.79
3528 2023-08-30    85.86   543.67  2140.25         464.80         945.40
3529 2023-08-31    86.86   545.00  2165.25         451.73         955.35

========================================
X.csv
shape:(9144, 2)
Period: ['1988-06-27T00:00:00.000000'] → ['2024-04-04T00:00:00.000000']
Columns and types:
Date     datetime64[us]
Price           float64
dtype: object

Nulls:
  Sin nulos

First rows:

        Date  Price
0 2024-04-04  89.18
1 2024-04-03  89.35
2 2024-04-02  88.92

Last rows:

           Date  Price
9141 1988-06-29  15.47
9142 1988-06-28  15.27
9143 1988-06-27  15.10

========================================
Y.csv
shape:(4485, 2)
Period: ['2006-07-11T00:00:00.000000'] → ['2023-09-12T00:00:00.000000']
Columns and types:
Date     datetime64[us]
Price           float64
dtype: object

Nulls:
  Sin nulos

First rows:

        Date   Price
0 2023-09-12  547.33
1 2023-09-11  546.00
2 2023-09-08  545.00

Last rows:

           Date  Price
4482 2006-07-13  555.0
4483 2006-07-12  555.0
4484 2006-07-11  555.0

========================================
Z.csv
shape:(3565, 2)
Period: ['2010-01-01T00:00:00.000000'] → ['2023-08-31T00:00:00.000000']
Columns and types:
Price           float64
Date     datetime64[us]
dtype: object

Nulls:
  Sin nulos

First rows:

     Price       Date
0  2225.25 2010-01-01
1  2225.25 2010-01-04
2  2246.50 2010-01-05

Last rows:

        Price       Date
3562  2116.25 2023-08-29
3563  2140.25 2023-08-30
3564  2165.25 2023-08-31

========================================

In [55]:
def df_normalitation(df:pd.DataFrame, date_col='Date') -> pd.DataFrame:
    """
    Order datetime values
    Pass the column Date to the first column
    """
    df = df.sort_values(by=date_col, ascending=False).reset_index(drop=True)
    columns = [date_col] + [col for col in df.columns if col != date_col]
    df = df[columns]
    
    return df

In [56]:
df_equipment_norm = df_normalitation(historical_equipment)
df_x_norm = df_normalitation(historical_x)
df_y_norm = df_normalitation(historical_y)
df_z_norm = df_normalitation(historical_z)

In [58]:
df_equipment_norm.head()

        Date  Price_X  Price_Y  Price_Z  Price_Equipo1  Price_Equipo2
0 2023-08-31    86.86   545.00  2165.25         451.73         955.35
1 2023-08-30    85.86   543.67  2140.25         464.80         945.40
2 2023-08-29    85.49   545.33  2116.25         460.42         901.79
3 2023-08-28    84.42   549.00  2116.25         469.03         933.20
4 2023-08-25    84.48   554.00  2123.50         450.36         899.65

In [ ]:
def validar_columna_historico(
    df_indiv: pd.DataFrame, 
    df_hist: pd.DataFrame, 
    indiv_col: str, 
    hist_col: str, 
    file_name: str
) -> None:
    """
    Validates that values from the individual artifacts match with historical 
    column data, using date as index
    """
    s1 = df_indiv.set_index('Date')[indiv_col]
    s2 = df_hist.set_index('Date')[hist_col]

    comp_df = pd.DataFrame({
        'Individual': s1,
        'Historical': s2
    }).dropna()

    are_close = np.isclose(comp_df['Individual'], comp_df['Historical'], rtol=1e-5, atol=1e-8)

    print(f"-- Validation for {file_name} --")    
    if all(are_close):
        print(" All values match perfectly")
    else:
        dif  = comp_df[~are_close]
        print(f"It founds {len(dif)} discrepancies")
        display(dif.head(10))
    print(f"{'='*40}")

In [80]:
validar_columna_historico(
    df_indiv=df_y_norm, 
    df_hist=historical_equipment, 
    indiv_col='Price', 
    hist_col='Price_Y', 
    artifact_name='Archivo y.csv'
)

<class 'numpy.ndarray'>
--- Validación para: Archivo y.csv (Price vs Price_Y) ---
Registros evaluados en el rango común: 3530
 Resultado: ¡Éxito! Todos los valores coinciden perfectamente.
========================================